### ISSUE TITLE
OCRNet performance problem

### ISSUE THREAD

**Issue by ICE-Bro** [RViMLab/ContrSegm#2]
Hi, thank you for the great work. But the performance of OCRNet combined with your method in Table 4 (b) confused me. As you didn't provide the reproduction result of OCRNet in Table 4 (b), I am wondering if the final performance was slightly attenuated due to poor reproduction result. I look forward to your early reply, thanks again.

**Comment by TheoPis** [comment]
Hi @ICE-Bro. Let me clarify. We indeed did not reproduce the performance of OCRNet on Cityscapes-test (mostly due to time constraints, as training on train+val takes a lot of time). We use the same training schedule from the OCRNet paper and just add our loss to the standard CE loss (in fact this is what we do throughout the paper).  
 It is possible that trying to reproduce the baseline result of OCRNet (i.e without our loss) with our code would not exactly match the published result (due to training stochasticity) but I expect it to be very close, but we have not checked. In any case, eventhough our method does slightly worse (-0.1%) in terms of overall miou, it improves other metrics by good margins.

**Comment by ICE-Bro** [comment]
> Hi @ICE-Bro. Let me clarify. We indeed did not reproduce the performance of OCRNet on Cityscapes-test (mostly due to time constraints, as training on train+val takes a lot of time). We use the same training schedule from the OCRNet paper and just add our loss to the standard CE loss (in fact this is what we do throughout the paper). It is possible that trying to reproduce the baseline result of OCRNet (i.e without our loss) with our code would not exactly match the published result (due to training stochasticity) but I expect it to be very close, but we have not checked. In any case, eventhough our method does slightly worse (-0.1%) in terms of overall miou, it improves other metrics by good margins.

Got it, thanks for responding so quickly to my question.
